src/parking.rs
Alternative to https://github.com/async-rs/async-std/pull/836/commits/d4572c794d2b1c38d3acaf1e327ff370e6c7b4d1
I guess it makes sense to do that here?
=> parking: ensure Reactor is initialized when creating a Parker

src/lib.rs
Maybe a comment would be useful? Something like "Workaround to check if there was an error while connecting."?
=> fail fast on `io::ErrorKind::NotConnected`

src/reactor.rs
calls to `std::mem::drop` with a reference instead of an owned value. Dropping a reference does nothing.
=> remove drop(self) when react

src/lib.rs, tests/async.rs
Warning: the second commit introduces a slight API break (the returned streams no longer implement `Unpin`). Perhaps you only want to take the first but not the second commit, or perhaps only release the second commit in the next API-breaking release.
As far as I can see, the only reason for `Async<T>` to use a `Box<T>` internally was for the `Async<T>` to be `Unpin`, no matter whether `T` itself is `Unpin` or not. But you can achieve that by just explicitly asking for it:
```rust
impl<T> Unpin for Async<T> {}
```
As `Async<T>` never creates a `Pin<&mut T>` or anything like that (that would be useless — most likely `T` is not a `Future` or a `Stream`), it is completely fine to just implement `Unpin` for the aggregate type (`Async<T>`) even if one of the fields is `!Unpin`. …
=> Less boxing

Cargo.toml, src/lib.rs, src/socket.rs
As discussed in #27. This pull request removes the `socket2` and `cfg-if` (was not being used?) dependencies. Most of the code is from rusts standard library and the `socket2` crate. I only implemented features that are actually used in `async-io` atm to keep the code base small.
=> remove socket2 dependency

Cargo.toml
Like [in](https://github.com/stjepang/polling/blob/master/Cargo.toml#L23) `polling` we only need `libc` on unix systems
=> remove `libc` dependency on windows

.github/workflows/build-and-test.yaml, .github/workflows/lint.yaml, .github/workflows/security.yaml, src/lib.rs, tests/timer.rs
Based on #35, needed to use async-io in more places in libp2p.
=> Add interval api.

src/lib.rs
~~These enable generic implementations for `Borrow<T>` and `BorrowMut<T>` to work on `Async<T>`.~~
These enable generic implementations for `AsRef<T>` and `AsMut<T>` to work on `Async<T>`.
=> impl AsRef<T> and AsMut<T> for Async<T>

Cargo.toml, src/lib.rs
Based on the discussion in https://github.com/smol-rs/nb-connect/pull/5, use socket2 directly instead of nb-connect.
=> Replace nb-connect with socket2

Cargo.toml, src/reactor.rs
slab provides similar functionality to vec-arena, but is [used much more widely in the ecosystem](https://crates.io/crates/slab/reverse_dependencies), has some additional useful methods, and is a bit more efficient as far as I know.
Also, this will reduce the dependencies when using this crate along with async-std, futures-util, hyper, etc (because they depend on slab).
Also, I'm considering deprecating vec-arena in favor of slab, because:
- slab is more powerful
- [slab is widely used in the ecosystem](https://crates.io/crates/slab/reverse_dependencies)
- [there are very few users of vec-arena](https://crates.io/crates/vec-arena/reverse_dependencies)
- I currently maintain virtually both crates and it's not fun to maintain multiple crates with the same content. And I basically …
=> Replace vec-arena with slab

src/lib.rs, src/reactor.rs
This replaces yanked #64.
- change `Readable` and `Writable` futures to contain a reference to `Async`
- add `Async::{readable_owned, writable_owned}` that take `self: Arc<Self>`
See https://github.com/smol-rs/async-io/pull/64#issuecomment-846432757 (and the comments before and after) for more.
r? @Kestrer @yoshuawuyts  @smol-rs/admins
=> Add Async::{readable_owned, writable_owned}

src/reactor.rs
This fixes a bug wherein the first timer set for exactly `now` ends up
in the `pending` list instead of the `ready` list, eventually resulting
in polling with a timeout of 0.
Under normal circumstances this bug would trigger very rarely, and when
it did would only result in one spurious "loop", since the next time the
timers are checked, time will have advanced.
However, this bug can cause misbehavior and deadlock in emulated
environments. e.g., in the [Shadow](https://shadow.github.io/) emulator, time only moves forward when
a blocking syscall is performed, so this bug causes deadlock:
https://gitlab.torproject.org/tpo/core/arti/-/issues/174#note_2762399
=> Process timers set for exactly `now`

src/lib.rs
Shrink unsafe block for the  Async impl
=> The scope of the unsafe block can be appropriately reduced

Cargo.toml, build.rs, src/lib.rs
This PR implements `AsFd` and `AsSocket` for `Async<T>`. In addition, `TryFrom<OwnedFd/OwnedSocket` is implemented for `Async<T>` and `TryFrom<Async<T>>` is implemented for `OwnedFd/OwnedSocket`, in order to mirror the `From/Into<OwnedFd/OwnedSocket>` impls in `std` but also considering that the operations are fallible in `async-io`.
See also: sunfishcode/io-lifetimes#38
=> Implement I/O-safe traits

src/lib.rs
This PR fixes two outstanding issues with timers:
- #86, where large `Duration`s can cause the `Timer` code to panic as a result of unchecked addition. This PR checks to ensure that the addition does not overflow; if it does, it returns an `Instant` in the far future.
- #42, suggesting that a blank `Timer` could exist that never fires. This not only adds a `blank` method that creates a timer that isn't registered in the `Reactor`, but also uses this method to implement `Default` on `Timer`.
Closes #86 
Closes #42
=> Improve timer functionality

Cargo.toml, benches/io.rs
I'd like to be able to tell if #85 positively or negatively impacts the performance of I/O (although my initial expectations is no effect at all). This PR adds a set of benchmarks that measure the performance of a number of operations.
Currently a work in progress that only measures reading/writing, and ideally would probably only measure one at a time.
=> Add basic benchmarking

src/lib.rs
Previously, in #87, I made it so that, when timers overflow, they're set to 30 years in the future by default. On reflection, however, it makes more sense for them to never go off on overflow. This PR makes that the new behavior.
=> Make it so timers never go off on overflow

Cargo.toml, src/driver.rs, src/reactor.rs
Resolves #93 by using the `OnceCell` type found in `async-lock`. This type allows for blocking operations, just like the `once_cell::Lazy` type that was used earlier. In addition, `async-lock` does not bump our MSRV, while `once_cell` does.
~~This is a draft PR because smol-rs/async-lock#27 has not yet been released~~
=> Use once_cell from async-lock

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml
Changes:
- Update `concurrent-queue` to v2. (#99)
=> Release 1.11.0

.github/workflows/ci.yml, Cargo.toml, examples/linux-timerfd.rs, src/lib.rs
Use the [rustix] syscall wrapper crate to factor out error handling and
unsafe system calls. This reduces the amount of unsafe code here, and is
a step towards factoring it out entirely once [`AsFd`] is stabilized and
can replace `AsRawFd` for these kinds of uses.
This does require incrementing the minimum required Rust version to 1.48.
Please feel free to decline this PR if you don't wish to take on these new
requirements.
[rustix]: https://crates.io/crates/rustix/
[`AsFd`]: https://doc.rust-lang.org/stable/std/os/unix/io/trait.AsFd.html
=> Use rustix instead of direct calls to libc.

src/lib.rs
This should clear up a small point of confusion regarding how precise the timers are allowed to be.
=> Add a small comment explaining timer precision

src/lib.rs
This PR adds a `will_fire` method to `Timer` that returns `true` if its `when` field is `Some`, indicating that it will eventually fire and won't just return `Pending`.
=> feat: Add will_fire method that indicates if a timer will fire

Cargo.toml, src/lib.rs
See https://github.com/smol-rs/async-process/pull/31#discussion_r1059223352 for the context.
=> Reduce syscalls in Async::new

src/reactor.rs
Removes the need for the `RemoveOnDrop` structure by implementing the drop logic directly on `Ready`.
=> m: Improve drop ergonomics of Ready

Cargo.toml, benches/timer.rs
From a failed attempt to see if we could speed up the reactor by dropping the `ConcurrentQueue` and just pushing the timers directly to the `BTreeMap`. Oh well, at least these benchmarks might be useful.
=> bench: Add benchmarks for timers

Cargo.toml, src/reactor.rs
Takes smol-rs/concurrent-queue#36 and uses it to drain timer operations from the timer operation queue.
=> m: Use try-iter for processing timers

.cirrus.yml, .github/workflows/ci.yml
=> ci: Fix cross builds in the CI

src/lib.rs
- Fix some broken documentation links.
- Fix vagueness in how `will_fire` will handle a `Timer` that has already fired.
=> docs: Fix various documentation issues for Timer

.cirrus.yml, .github/workflows/ci.yml
See https://github.com/smol-rs/polling/pull/110 for the context.
=> Use Cirrus CI for NetBSD/OpenBSD

Cargo.toml, src/lib.rs
This PR removes the unused fastrand and memchr dependencies, which were previously indirectly depended on through `futures-lite`. This PR makes it so `futures-lite` has no default features. We also manually import `AsyncRead`/`AsyncWrite` through `futures-io`.
=> Remove fastrand and memchr dependencies

Cargo.toml, src/driver.rs, src/reactor.rs
cc smol-rs/smol#244, smol-rs/polling#119, smol-rs/blocking#40
Replaces `log` with `tracing`
=> Replace log with tracing

src/os.rs, src/os/unix.rs, src/reactor.rs
Closes #124 by adding a method `async_io::os::unix::reactor_fd()` that allows one to get the file descriptor to register `async-io`'s reactor into an external runtime.
=> feat: Add a way to get the global poller's fd

.github/workflows/ci.yml, src/reactor.rs
The `TimerOp` struct size - depending on the platform - is anything between 20 to 28 bytes (if not more due to alignment). When multiplied by 1000 timers for the bounded queue we get into 20K to 30K RAM usage.
Minuscule amount for regular machines or even for embedded-Linux SOCs, but quite a lot for MCUs which have 200 to 400K RAM.
Reducing the queue to 100 timers seems reasonable to me, because I don't expect hundreds of timers to be used on that platform.
=> Support for the ESP-IDF framework

Cargo.toml
Reverts smol-rs/async-io#133
Fixes OpenBSD CI.
(The equivalent is contained in another PR, but that PR is a bit controversial, so I address this issue first to avoid blocking the other PRs.)
=> Revert "Update criterion requirement from 0.4 to 0.5"

src/driver.rs, tests/block_on.rs
`async-io`'s implementation of `block_on` currently creates a new parker and waker on every invocation. This PR caches the parker and waker in a thread-local to improve performance. Most of this code is copied from [`futures-lite`'s implementation of `block_on`](https://github.com/smol-rs/futures-lite/blob/2234456b71cd5d20d67c3ee4c5e3c97a25912612/src/future.rs#L56), as that crate already does exactly this, and the performance difference between these two `block_on` implementations is why I looked into optimizing `async-io` in the first place.
<details><summary>futures-lite (Red) vs async-io without this PR (Yellow)</summary>
<p>
</p>
</details> 
<details><summary>futures-lite (Red) vs async-io with this PR (Yellow)</summary>
<p>
</p>
</details> 
(Also see …
=> Optimize block_on by caching Parker and Waker

Cargo.toml, src/lib.rs, tests/async.rs
socket2 is our last libc-using dependency. By replacing it with rustix calls, we can make this crate libc-free.
This doesn't set the inherit disable property on Windows yet, as rustix does not support it.
=> Replace socket2 calls with rustix

src/reactor/kqueue.rs, src/reactor/unix.rs, src/reactor/windows.rs
All callers already pass Borrowed*.
=> Remove needless as_fd/as_socket calls

src/lib.rs
On Unix, we are already using it.
=> Use set_nonblocking in Async::new on Windows

Cargo.toml, src/lib.rs, src/os/kqueue.rs
Our MSRV (1.63) is higher than 1.56 that Rust 2021 was stabilized.
=> Migrate to Rust 2021

src/lib.rs
connect() already sets socket to non-blocking mode.
The second comment exposes Async::new_nonblocking to resolve https://github.com/smol-rs/async-io/issues/132.
=> Add Async::new_nonblocking and avoid needless set_nonblocking calls

.github/workflows/ci.yml, src/lib.rs
I forgot to implement IoSafe on these during the initial switch to polling v3.0.0
=> Implement IoSafe for the child process stdio types

Cargo.toml, src/driver.rs
Resolves https://github.com/smol-rs/async-io/issues/165
Adds a new concrete type `BlockOnWaker` that implements `Wake`
=> Remove dependency on waker-fn

src/lib.rs, tests/async.rs
In #146, I introduced a bug that prevented abstract sockets from
working. I passed the path straight into
rustix::net::SocketAddrUnix::new, which fails if it receives an abstract
socket.
This commit fixes this issue by explicitly checking for abstract
sockets. If it sees that the path it's receiving is abstract, it will
pass the path's bytes to new_abstract_socket() instead.
This should fix the issue that is occurring in dbus2/zbus#517
=> Add support for abstract sockets

.cirrus.yml, .github/workflows/ci.yml, src/driver.rs
- Use const thread_local
This is available since Rust 1.59 (https://github.com/rust-lang/rust/pull/91355).
- Fix CI failure due to FreeBSD 12.4 EoL
- Use cargo-hack's --rust-version flag for msrv check
This respects rust-version field in Cargo.toml, so it removes the need to manage MSRV in both the CI file and Cargo.toml.
=> Use const thread_local & Fix CI failure

examples/windows-command.rs, src/lib.rs, src/os.rs, src/os/windows.rs, src/reactor/windows.rs
This commit allows waitable handles to be polled in Windows. This allows I/O constructs like processes, mutexes and waitable events be registered into the poller and be polled just like anything else.
cc #25
=> Expose waitable handles in Windows

src/lib.rs, tests/issue_182.rs
This commit adds a setup_networking function. On most platforms it does
nothing. However, on Windows it calls `wsa_startup`. This ensures that
all networking is set up before anything else is called.
Closes #182
=> Initialize networking on Windows

.cirrus.yml, tests/issue_182.rs
- Fix a previously unnoticed TCP error on NetBSD
- Our tests MSRV is too high, just build on OpenBSD
=> Fix BSD CI failures

src/lib.rs
AIX has neither SOCK_NONBLOCK nor SOCK_CLOEXEC flags.
=> Fix SocketFlags usage on AIX

Cargo.toml, src/lib.rs
Follow-up to https://github.com/smol-rs/async-io/pull/146#discussion_r1318111984.
rustix 0.38.18+ supports it (https://github.com/bytecodealliance/rustix/pull/870) and std now sets it on these targets (https://github.com/rust-lang/rust/pull/124470#issuecomment-2081489885).
=> Set nosigpipe on NetBSD and DragonFly BSD

examples/kqueue-process.rs, src/os/kqueue.rs, src/reactor/kqueue.rs
These change loose the BSD systems API when creating an Exit struct. At the moment, the Exit struct takes ownership of the Child struct and not publicly exporting it, preventing being able to call Child's methods.  
The Exit struct is primarily used to wait for a child process termination using the reactor's registration functionality. The Registration uses the polling crate to perform the async wait. The polling only requires a PID, thus these changes removes the child ownership from the package in favor of just providing a PID number.
This will ease the development of the `async-process` for BSD systems: https://github.com/smol-rs/async-process/issues/49#issuecomment-2385345337
=> refactor: remove child ownership from Exit filter

.cirrus.yml
Disabled since https://github.com/smol-rs/async-io/pull/184, no longer needed since https://github.com/smol-rs/async-io/pull/210.
=> ci: Run test on OpenBSD again

src/reactor.rs
It seems the comment was not updated after [this](https://github.com/smol-rs/async-io/commit/86b340b50f444bd97c1b6e6880f47c92f65dee74#diff-29275b5ad58035009f3e141cfb1b1c1a800ad812070713f60ef91860fd816696R461).
=> nit: Fix comment in ReactorLock::react

.github/workflows/ci.yml, src/lib.rs
Related: https://github.com/bytecodealliance/rustix/pull/411
=> Add support for Haiku

Cargo.toml, build.rs, src/lib.rs
It would be handy to have async wrappers for the pipe types (from std::io::pipe()), so impl IoSafe for both.
The pipe types were introduced in 1.87, but the MSRV for async-io appears to be 1.63 currently. So, protect the impls with a cfg(has_pipe), and use autocfg to set has_pipe, like was done in a20076f ("Implement I/O-safe traits (#84)")
=> impl IoSafe for std::io::PipeReader & std::io::PipeWriter

src/lib.rs
=> Add Timer::pause

src/lib.rs
Two examples are shown in [`Timer`'s docs](https://docs.rs/smol/latest/smol/struct.Timer.html):
One example for basic _sleeping_ and one example for having a _timeout_ on a future.
This adds corresponding doc aliases to `Timer`, so that this struct is easier to find with those use cases in mind.
See doc alias feature:
https://blog.rust-lang.org/2020/11/19/Rust-1.48/#adding-search-aliases
=> Add doc aliases `sleep` and `timeout` to `Timer`

CHANGELOG.md, Cargo.toml
Changes:
- Bump MSRV to 1.71. (#243)
- Expose `Timer::clear`. (#239)
- Implement `IoSafe` for `std::io::PipeReader` and `std::io::PipeWriter` (#237)
- Update to `windows-sys` v0.61. (#243)
- Remove dependency on `async_lock`. (#240)
=> Release 2.6.0
